### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by michaelarnauts**
I'm working on a rewrite of the library that fixes a few open issues.
* Cleaner code
* Better volume setting
* Logging

It won't be backwards compatible with the existing code, so I will probably use a new version for this.

### CODE REVIEW

**Comment by tlk** [comment]
This script looks like just what I was looking for, thanks!

From the [network graph](https://github.com/michaelarnauts/cec-mqtt-bridge/network) it appears to be common for people to remove IR-support. Perhaps you could consider separating out the IR logic into a separate but almost identical project? Fx "ir-mqtt-bridge". This would align well with the "do one thing and do it well" unix philosophy.

Best,
  Thomas

**Comment by michaelarnauts** [comment]
IR is currently broken in this branch, maybe it does make sense to split it off to a separate project, I haven't thought about this. But it shouldn't matter that much, if you disable IR in the config, it won't be initialised.

**Comment by tlk** [comment]
That's right, although requirements.txt still reference python-lirc.

On another note, I have been looking at this [cec python library](https://github.com/trainman419/python-cec) which is available on pypi.org and [piwheels.org (well, not yet but possibly soon-ish)](https://github.com/piwheels/packages/issues/73#issuecomment-571987160)

The API is different (notably [libcec_configuration is not implemented](https://github.com/trainman419/python-cec/blob/9b8e777a4ace13da2806ab2ec973950219db92eb/cec.cpp#L781-L786)) but I think the installation process would be simplified without the need for locally compiled python bindings.

Just wanted to share with you as I am interested in your thoughts on this.

**Comment by michaelarnauts** [comment]
I've looked at that library also, but it had some strange delays. When I send a command, it had a 2 seconds delay of something. I haven't looked at it further.

**Comment by michaelarnauts** [comment]
It seems like I have been running these changes for over 2 years, so I might as well merge them :)

**Pull request merged**
