### PR TITLE
Lirc improvement

### PR DESCRIPTION
**Pull request by janLo**
This improves teh lirc support. It includes the remote in the mqtt topic (if available from lirc). It also adds a script to generate an lircrc config.

### CODE REVIEW

**Comment by michaelarnauts** [comment]
Cool! Thanks! Can you also update the example `lircrc.default` file to include the `remote` in the config? This way it matches with the output of your script.

Maybe you can add a note about the backward compability if you only specify a key in the config?

**Comment by janLo** [comment]
The old config should work unchanged without any problem. But I will add more documentation after the weekend.

**Comment by janLo** [comment]
@michaelarnauts I added documentation and extended teh example lircrc config.

**Comment by michaelarnauts** [comment]
Sorry for the delay. Thanks for your update!

**Pull request merged**
